#! /bin/bash
# these are commands that are needed to run node.js on the remote host

sudo apt-get -y update
sudo apt-get -y install python-software-properties python g++ make
sudo add-apt-repository -y ppa:chris-lea/node.js
sudo apt-get -y update
sudo apt-get -y install nodejs
# wget raw.github.com/startup-class/dotfiles/master/.screenrc -O .screenrc
sudo apt-get install -y git-core
wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

npm install restler 
npm install cheerio
npm install commander


