#! /bin/bash
#  authorization information is now set in ~/.ssh/config
# so the work with the AWSAUTH env-var is superfluous now

REMTOE=${1?Remote host to connect to?}
AWSAUTH=~/.ssh/chris-duncombe-rae.pem

# echo Copying startup script
# scp -i $AWSAUTH  startup.script ubuntu@$REMTOE:

# echo Copying github keys
scp -i $AWSAUTH  /home/duncombe/.ssh/github_key{,.pub} ubuntu@$REMTOE:.ssh/ ||
	{ echo Transfer github keys failed ; exit 1 ; }

# Create a useful ssh_config
( ssh -i $AWSAUTH  ubuntu@$REMTOE cat \> .ssh/config << ENDIN 
Host github github.com
        Hostname github.com
        User git
        IdentityFile ~/.ssh/github_key
	StrictHostKeyChecking   no 

# vim:  se nowrap tw=0 :
ENDIN
) || { echo Creating .ssh/config file failed ; exit 2 ; }

# install git-core so we can continue
ssh -i $AWSAUTH   ubuntu@$REMTOE sudo apt-get install -y git-core

# clone the setup script out of github
ssh -i $AWSAUTH   ubuntu@$REMTOE git clone github:duncombe/setup

# run the setup script
ssh -i $AWSAUTH   ubuntu@$REMTOE setup/setup.sh

# start an interactive shell
ssh -i $AWSAUTH   ubuntu@$REMTOE

# vim: se nowrap tw=0 :
 
